# Basic hyprlock configuration

general {
    no_fade_duration = 0.2
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot # takes a screenshot and uses it as background
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 2 # 0 disables blurring
    blur_on_window = true
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.2993
    angle = 131.7
    scale = 0.7
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    inside_corner_radius = 10
    border-size = 4
    border_color = rgb(200, 200, 200)
    inside_color = rgb(30, 30, 46)
    font_family = JetBrainsMono Nerd Font
    font_size = 20
    layout_file = ~/nwg-look/keyboard-layout.conf # supports own layout file
    placeholder_text = <i>Password...</i>
    shadow_radius = 10
    shadow_colorize = true
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    align = center
}
